### PR TITLE
Initially add DEPTH into ColorFormat

### PR DESCRIPTION
**Pull request by huningxin**
Address https://github.com/kakukogou/spec-imagebitmap-extension/issues/1

### CODE REVIEW

**Comment by anssiko** [comment]
Would GRAY16 work for depth, since there's GRAY8 already in the spec? http://kakukogou.github.io/spec-imagebitmap-extension/#idl-def-ColorFormat

In WebGL that'd be LUMINANCE16. Ping @ds-hwang to chime in.

**Comment by ds-hwang** [comment]
GRAY16 is exactly same to LUMINANCE16 without name. It's very aligned to WebGL as well as underlining media pipeline. So depth should use ImageBitmap with GRAY16 color format.
I think DEPTH is ambiguous and is usage instead of color format

**Comment by huningxin** [comment]
I prefer to `DEPTH` as it indicates depth map pixel format specifically. Developers would use the value of `DEPTH` together with `units`, `near` and `far` [depth related attributes of MediaTrackSettings](http://w3c.github.io/mediacapture-depth/#mediatracksettings-dictionary).

`GRAY16` is another color format. I am not objective to add it in another PR if @kakukogou agrees. 

I also suggest to change `ColorFormat` to `PixelFormat` or `ImageFormat` (suggested by @anssiko) to accommodate `DEPTH`.

Thoughts?

**Comment by kakukogou** [comment]
I would prefer to rename the <code>ColorFormat</code> to <code>ImageFormat</code> if we want to add depth-related items into the enumeration.

Also, I think <code>DEPTH</code> is much more specific even though it is technically the same to  <code>GRAY16</code>. One question, does depth data always use 16 bits per pixel?

**Comment by ds-hwang** [comment]
Currently, depth format is unsigned 16 bit int in depthcapture spec. However, I'm not sure if depth format will be extended in the future. @huningxin, @anssiko WDYT?

the pixel format should demonstrate exact pixel layout. if depth format is extended, DEPTH will be in trouble.

**Comment by huningxin** [comment]
> One question, does depth data always use 16 bits per pixel?

The 16 bits per pixel DEPTH format is close to today's depth camera output and widely used in native SDK:

Intel RealSense SDK:
https://software.intel.com/en-us/intel-realsense-sdk/download
PIXEL_FORMAT_DEPTH: the depth map data in **16-bit unsigned integer**. The values indicate the distance from an object to the camera's XY plane or the Cartesian depth. The value precision is in **millimeters**. 

Microsoft Kinect SDK:
https://msdn.microsoft.com/en-us/library/microsoft.kinect.kinect.idepthframe.aspx
The data for this frame is stored as **16-bit unsigned integers**, where each value represents the distance in **millimeters**. The maximum depth distance is 8 meters, although reliability starts to degrade at around 4.5 meters. Developers can use the depth frame to build custom tracking algorithms in cases where the IBodyFrame isn’t enough.

Google Project Tango:
According to Tango Depth Camera implementation in Chromium (https://code.google.com/p/chromium/codesearch#chromium/src/media/base/android/java/src/org/chromium/media/VideoCaptureTango.java&q=tango&sq=package:chromium&l=141),

```
// Depth is composed of 16b samples in which only 12b are
// used.
```

It is also uint16.

> the pixel format should demonstrate exact pixel layout. if depth format is extended, DEPTH will be in trouble.

We can extend it with another enum. For example, if depth camera evolves to support `float` output, we can add DEPTH_F32.

**Comment by huningxin** [comment]
> I would prefer to rename the ColorFormat to ImageFormat if we want to add depth-related items into the enumeration.

Change the `ColorFormat` to `ImageFormat`.

Add add a depth image pixel layout format.

@kakukogou @anssiko @ds-hwang , please review. Thanks.

**Comment by kakukogou** [comment]
Directly changing the <em>color format</em> to <em>image format</em> in description sections make the paragraphs' structure/meaning somewhat unorganised. I think I will rephrase description sections to adopt the depth concept in the way that COLOR formats and the DEPTH format are cases of generalised <code>ImageFormat</code>. 

Other changes looks good to me.

**Comment by huningxin** [comment]
@kakukogou , thanks for your review. Your comments make sense. I restore the changing of _color format_ to _image format_ in description sections. 

Please take another look. Thanks!

**Comment by anssiko** [comment]
Thanks @huningxin, your changes look good to me with @kakukogou's comments on rephrasing.

**Pull request merged**
